name: BuyNova Deploy Firebase Functions

on:
  workflow_dispatch:
  push:
    paths:
      - "functions/**"
      - ".github/workflows/firebase-functions.yml"
    branches:
      - main

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Firebase Functions dependencies
        working-directory: functions
        run: npm install

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Show authenticated account
        run: |
          gcloud auth list --filter=status:ACTIVE --format="value(account)"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project buynova-cc5dd --non-interactive --force
